import Head from 'next/head'
export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/cs-icon.svg" />
      </Head>
      <h1 className='text-5xl'>Hello World</h1>
      
    </div>
  )
}
